name: flutter_mvr
description: A Flutter MVR pattern package. Helps keep things organized
version: 0.0.1
homepage: https://github.com/JakubWasilczyk/flutter_mvr

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.3.1
  equatable: ^2.0.5
  meta: ^1.8.0
  path: ^1.8.2
  pub_semver: ^2.1.1
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/generator/templates/