name: flutter_mvr
description: A Flutter MVR pattern package. Helps keep things organized
version: 0.0.1
homepage: https://github.com/JakubWasilczyk/flutter_mvrs

environment:
  sdk: ">=2.17.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: