targets:
  $default:
    builders:
      model_generator:
        enabled: true
        options:
          build_extensions:
            '^lib/models/{{}}.dart': 'lib/models/base/{{}}.base.dart'

builders:
  model_generator:
    import: "package:flutter_mvrs/builder.dart"
    builder_factories: ["modelBuilder"]
    build_extensions: { ".dart": [".base.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]