targets:
  $default:
    builders:
      model_generator:
        enabled: true
        options:
          build_extensions:
            "{{}}.dart": "base/{{}}.base.dart"

builders:
  model_generator:
    import: "package:flutter_mvrs/builder.dart"
    builder_factories: ["modelBuilder"]
    build_extensions: { "{{}}.dart": "base/{{}}.base.dart" }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]