builders:
  model_generator:
    import: "package:flutter_mvrs/builder.dart"
    builder_factories: ["modelBuilder"]
    build_extensions: { ".dart": [".base.dart"] }
    auto_apply: dependents
    build_to: source