name: flutter_mvr_example
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_mvr:
    git:
      url: git@github.com:JakubWasilczyk/flutter_mvr.git
      path: flutter_mvr

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  flutter_mvr_builder:
    path: ../flutter_mvr_builder


flutter:
  uses-material-design: true































